import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/reduxProvider/ReduxProvider";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider/Theme-provider";
import ProgressBar from "@/components/progressBar/ProgressBar";
import NextUiProvider from "@/components/NextUIProvider/NextUiProvider";
import {Comfortaa,Sarabun} from "next/font/google"

const inter = Inter({ subsets: ["latin"] });
const comforta = Sarabun({
  weight:["100","200","300","400","500","600","700"],
  subsets:["vietnamese"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <NextUiProvider>
          <ProgressBar />

          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ReduxProvider>
              {children} <Toaster />
            </ReduxProvider>
          </ThemeProvider>
        </NextUiProvider>
      </body>
    </html>
  );
}
